### ISSUE TITLE
Over-Read request sent to origin when issued a pgRead

### ISSUE THREAD

**Issue by djw8605** [PelicanPlatform/xrdcl-pelican#13]
When XRootD sends a pgRead to the pelican plugin, the last block may request more bytes than the size of the file, such that offset + request_size > file_size.  The built-in http plugin catches this case and restricts requests to the file_size maximum file size: [XrdClHttpFilePlugin.cc](https://github.com/xrootd/xrootd/blob/eb4295e0a2fc17c2210186424f949001eb4af93f/src/XrdClHttp/XrdClHttpFilePlugIn.cc#L249)

When the requested bytes range is larger than the size of the file, the xrootd origin will return the response headers, then close the connection without sending the data.  This causes the curl library to return error code 18: `transfer closed with outstanding read data remaining`.  I have replicated this error with multiple production pelican caches:

```
curl --output /dev/null http://osg-chicago-stashcache.nrp.internet2.edu:8443/icecube/PUBLIC/groups/arasoft/raytrace_timing_tables/arrivaltimes_station_100_icemodel_40_radius_300.00_angle_1.00_solution_0.root
curl --output /dev/null https://sdsc-cache.nationalresearchplatform.org:8443//icecube/PUBLIC/groups/arasoft/raytrace_timing_tables/arrivaltimes_station_100_icemodel_40_radius_300.00_angle_1.00_solution_0.root
curl --output /dev/null https://osg-sunnyvale-stashcache.nrp.internet2.edu:8443//icecube/PUBLIC/groups/arasoft/raytrace_timing_tables/arrivaltimes_station_100_icemodel_40_radius_300.00_angle_1.00_solution_0.root
```

The pelican platform should restrict the maximum size requested from the origin to the file size, similar to how the built-in http plugin.

**Comment by bbockelm** [comment]
IIRC, we tracked this down to an invalid response from an older version of the XRootD HTTP server.  The `xrdcl-pelican` behavior could be slightly improved but is correct in the presence of a well-behaved server.

Closing as "won't fix" unless we come up with another case where this bites us.
